api_content = {
    'Data': '/Date(1690217747176-0300)/',
    'DataVersao': '24/07/2023',
    'SessaoExpirada': False,
    'Cia': [
        {
            'Id': 0,
            'CodigoIata': 'G3',
            'Descricao': 'Gol Linhas Aéreas'
        },
        {
            'Id': 0,
            'CodigoIata': 'JJ',
            'Descricao': 'Tam'
        }
    ],
    'DataIda': '/Date(1692759600000-0300)/',
    'DataVolta': '/Date(-62135589600000-0300)/',
    'Destino': {
        'Id': 0,
        'CodigoIata': 'CGH',
        'Descricao': 'SAO PAULO - Congonhas (CGH)'
    },
    'Exception': None,
    'ExceptionPorSistema': None,
    'Origem': {
        'Id': 0,
        'CodigoIata': 'SDU',
        'Descricao': 'RIO DE JANEIRO - Santos Dumont (SDU)'
    },
    'QuantidadeAdultos': 1,
    'QuantidadeBebes': 0,
    'QuantidadeCriancas': 0,
    'Recomendacoes': None,
    'Rota': 'D',
    'TempoPesquisa': '00:00:00.4160000',
    'ViagensMultiplosTrechos': None,
    'ViagensTrecho1': [
        {
            'CiaMandatoria': {
                'Id': 0,
                'CodigoIata': 'G3',
                'Descricao': 'Gol Linhas Aéreas'
            },
            'Destino': {
                'Id': 0,
                'CodigoIata': 'CGH',
                'Descricao': 'CGH - SAO PAULO'
            },
            'Duracao': 65,
            'Fornecedor': {
                'Id': 0,
                'Codigo': 70,
                'Nome': 'Gol_GWS'
            },
            'Id': 65585,
            'IdentificacaoDaViagem': 'tQkAAB+LCAAAAAAABAC9lm1v2jAQx79K5b3lISEwaN6FoIRMASIKVaWqmkzigFUTR3bYmBAfaJ9jX2y2E5LCUq0waYiHs+/uz/3urCQHYAFTbwAbmFoDDNW3swdmDAlHDfCAOTD7mjK8CJjdexGKITCBa4AGmLymZWigFlpLBC9wSpXqCPEMJ1RoPB/ATGQ9jJYibSQs2x0LKxBWR+sYTW3Q7BgLTTPVW3jmwqNpmt5U78pzfBFlQo5sAjlHImgG8o0FZDgWH1ncbPrFstyuK1z59oJmkACzY/Rb99ppc5YiBiPKYMnwSItaJy5LC21fFgLOsCNeLCi583GygfzO+vWTIciF06o4rQp09HBOqmum0ctJx9Kla0ZPhtkXYbrZLRoyli5d70p7utuqHF3m2DSphnC+ED0qKALRIkFd9kaXvXkzsuEfzmGRLU1H/Aaq0cHJ8kKayPZvsizlZrv9ndIVbHKYRCu6b2UMfkOE4OS1FdJta8Xay5RQGLUJXdMtZCHkbeFIYbLBEIe011rjWKg6cIuJ7O0BTOlW6geMbqmijPCanv49X3lJhlhSbgYMxXivlvM8SCJ96g86aGDka4eKFLkZqxc4il11kPKx2/OiXY593gwHMrT4kYrUZ3H+ynYEE8hed6ceBrZV+HOKUXEm/ycNwTyTRRwbtTRep57GX9xC4+P1JntLo2QuaXLtksb33IpGv4f9QXQrjWu8Mxv/ptmQHT8bjV83Gv98NP6yghnAVTdCN8N062EmT7fATOD+LYsSuWTJlUuWifVUscSr3kqP/87yUtoH8AiJStbVZXctLIfIE+IlEZLVzFGMGEpCDANRnbqyeEkMkwyT4pp1rBcs9RZ0xwQF+phYo1L43Cs1sh2zQsQ5/epFV+u4M/9uPJvM/JlbI6h6f7XkfDkc1Ygt+U4MlV6vJ25qpEZvjsId4x/Xu8y3GYpUErmhb47cqCkqP9ZWhr9dDzpFyUbcB98TVQ8h12pqDXWvrVfMg/7t6C0THMEIcfXsEWKaQMzzP+EfbevL8TfNLlpJtQkAAA==',
            'NumeroParadas': 0,
            'Origem': {
                'Id': 0,
                'CodigoIata': 'SDU',
                'Descricao': 'SDU - RIO DE JANEIRO'
            },
            'Preco': {
                'Id': 0,
                'EqCambio': 0,
                'EqMoeda': None,
                'Moeda': 'BRL',
                'PrecoAdulto': {
                    'Id': 0,
                    'EqValorTarifa': 0,
                    'EqValorTaxaServico': 0,
                    'FaixaEtaria': 'ADT',
                    'Quantidade': 1,
                    'ValorFee': 1.0,
                    'ValorRav': 0,
                    'ValorTarifa': 237.9,
                    'ValorTarifaNet': 237.9,
                    'ValorTaxaAssento': 0,
                    'ValorTaxaBagagem': 0,
                    'ValorTaxaCombustivel': 0,
                    'ValorTaxaEmbarque': 42.29,
                    'ValorTaxaMenorDesacompanhado': 0,
                    'ValorTaxaServico': 40
                },
                'PrecoBebe': None,
                'PrecoCrianca': None,
                'Tarifa': 0,
                'TarifaOperadora': False,
                'TarifaPrivada': False,
                'Taxa': 82.29,
                'Total': 321.19,
                'TotalGeral': 321.19,
                'TotalTarifa': 237.9,
                'TotalTarifaNet': 237.9,
                'TotalTaxaAssento': 0,
                'TotalTaxaBagagem': 0,
                'TotalTaxaDeCombustivel': 0,
                'TotalTaxaEmbarque': 42.29,
                'TotalTaxaMenorDesacompanhado': 0,
                'TotalTaxaServico': 40,
                'ValorEMD': 0,
                'ValorFEE': 1.0,
                'ValorRAV': 0
            },
            'Rota': None,
            'Segmento': 'I',
            'SubFornecedor': None,
            'TempoDeDuracao': '01:05',
            'Voos': [
                {
                    'Id': 0,
                    'BagagemInclusa': False,
                    'BagagemIndicador': 2,
                    'BagagemPeso': 0,
                    'BagagemQuantidade': 0,
                    'BagagemUnidadeDeMedida': 'KG Total',
                    'BaseTarifaria': [
                        {
                            'Id': 0,
                            'Classe': '',
                            'Codigo': 'ONJAAG1G',
                            'Familia': 'PO'
                        }
                    ],
                    'Cabine': '',
                    'Campo1': None,
                    'CiaMandatoria': {
                        'Id': 0,
                        'CodigoIata': 'G3',
                        'Descricao': 'Gol Linhas Aéreas'
                    },
                    'CiaOperacional': {
                        'Id': 0,
                        'CodigoIata': 'G3',
                        'Descricao': 'Gol Linhas Aéreas'
                    },
                    'Classe': 'O',
                    'Companhia': None,
                    'Conexao': False,
                    'DataChegada': '/Date(1692801600000-0300)/',
                    'DataSaida': '/Date(1692797700000-0300)/',
                    'Destino': {
                        'Id': 0,
                        'CodigoIata': 'CGH',
                        'Descricao': 'CGH - SAO PAULO'
                    },
                    'Duracao': '01:05',
                    'Equipamento': '738',
                    'Escalas': None,
                    'Familia': 'Promo',
                    'FamiliaCodigo': 'PRO',
                    'GrupoDeSegmento': 0,
                    'HoraChegada': '1140',
                    'HoraSaida': '1035',
                    'Icone': 'https://wooba-sandbox.travellink.com.br/Upload/logomarcas/companhiaico5.gif',
                    'Linha': None,
                    'ListaDeClasses': [
                        {
                            'BagagemInclusa': False,
                            'BagagemIndicador': 2,
                            'BagagemPeso': 0,
                            'BagagemQuantidade': 0,
                            'BagagemUnidadeDeMedida': 'KG Total',
                            'BaseTarifaria': 'ONJAAG1G',
                            'Cabine': 'Econômica',
                            'Classe': 'O',
                            'Familia': 'Promo',
                            'FamiliaCodigo': 'PRO',
                            'Moeda': 'BRL',
                            'Perfil': None,
                            'Preco': {
                                'Id': 0,
                                'EqCambio': 0,
                                'EqMoeda': None,
                                'Moeda': 'BRL',
                                'PrecoAdulto': {
                                    'Id': 0,
                                    'EqValorTarifa': 0,
                                    'EqValorTaxaServico': 0,
                                    'FaixaEtaria': 'ADT',
                                    'Quantidade': 1,
                                    'ValorFee': 1.0,
                                    'ValorRav': 0,
                                    'ValorTarifa': 237.9,
                                    'ValorTarifaNet': 237.9,
                                    'ValorTaxaAssento': 0,
                                    'ValorTaxaBagagem': 0,
                                    'ValorTaxaCombustivel': 0,
                                    'ValorTaxaEmbarque': 42.29,
                                    'ValorTaxaMenorDesacompanhado': 0,
                                    'ValorTaxaServico': 40
                                },
                                'PrecoBebe': None,
                                'PrecoCrianca': None,
                                'Tarifa': 0,
                                'TarifaOperadora': False,
                                'TarifaPrivada': False,
                                'Taxa': 82.29,
                                'Total': 321.19,
                                'TotalGeral': 321.19,
                                'TotalTarifa': 237.9,
                                'TotalTarifaNet': 237.9,
                                'TotalTaxaAssento': 0,
                                'TotalTaxaBagagem': 0,
                                'TotalTaxaDeCombustivel': 0,
                                'TotalTaxaEmbarque': 42.29,
                                'TotalTaxaMenorDesacompanhado': 0,
                                'TotalTaxaServico': 40,
                                'ValorEMD': 0,
                                'ValorFEE': 1.0,
                                'ValorRAV': 0},
                            'TarifaAdulto': 237.9,
                            'TarifaBeba': 0,
                            'TarifaCrianca': 0,
                            'Tipo': 'OW'
                        },
                        {
                            'BagagemInclusa': False,
                            'BagagemIndicador': 2,
                            'BagagemPeso': 0,
                            'BagagemQuantidade': 0,
                            'BagagemUnidadeDeMedida': 'KG Total',
                            'BaseTarifaria': 'ONJAAI2G',
                            'Cabine': 'Econômica',
                            'Classe': 'O',
                            'Familia': 'Light',
                            'FamiliaCodigo': 'LIG',
                            'Moeda': 'BRL',
                            'Perfil': None,
                            'Preco': {
                                'Id': 0,
                                'EqCambio': 0,
                                'EqMoeda': None,
                                'Moeda': 'BRL',
                                'PrecoAdulto': {
                                    'Id': 0,
                                    'EqValorTarifa': 0,
                                    'EqValorTaxaServico': 0,
                                    'FaixaEtaria': 'ADT',
                                    'Quantidade': 1,
                                    'ValorFee': 1.0,
                                    'ValorRav': 0,
                                    'ValorTarifa': 252.9,
                                    'ValorTarifaNet': 252.9,
                                    'ValorTaxaAssento': 0,
                                    'ValorTaxaBagagem': 0,
                                    'ValorTaxaCombustivel': 0,
                                    'ValorTaxaEmbarque': 42.29,
                                    'ValorTaxaMenorDesacompanhado': 0,
                                    'ValorTaxaServico': 40
                                },
                                'PrecoBebe': None,
                                'PrecoCrianca': None,
                                'Tarifa': 0,
                                'TarifaOperadora': False,
                                'TarifaPrivada': False,
                                'Taxa': 82.29,
                                'Total': 336.19,
                                'TotalGeral': 336.19,
                                'TotalTarifa': 252.9,
                                'TotalTarifaNet': 252.9,
                                'TotalTaxaAssento': 0,
                                'TotalTaxaBagagem': 0,
                                'TotalTaxaDeCombustivel': 0,
                                'TotalTaxaEmbarque': 42.29,
                                'TotalTaxaMenorDesacompanhado': 0,
                                'TotalTaxaServico': 40,
                                'ValorEMD': 0,
                                'ValorFEE': 1.0,
                                'ValorRAV': 0
                            },
                            'TarifaAdulto': 252.9,
                            'TarifaBeba': 0,
                            'TarifaCrianca': 0,
                            'Tipo': 'OW'
                        },
                        {
                            'BagagemInclusa': True,
                            'BagagemIndicador': 3,
                            'BagagemPeso': 23,
                            'BagagemQuantidade': 1,
                            'BagagemUnidadeDeMedida': 'KG PER BAG',
                            'BaseTarifaria': 'ONJAAG3G',
                            'Cabine': 'Econômica',
                            'Classe': 'O',
                            'Familia': 'Plus',
                            'FamiliaCodigo': 'PLU',
                            'Moeda': 'BRL',
                            'Perfil': None,
                            'Preco': {
                                'Id': 0,
                                'EqCambio': 0,
                                'EqMoeda': None,
                                'Moeda': 'BRL',
                                'PrecoAdulto': {
                                    'Id': 0,
                                    'EqValorTarifa': 0,
                                    'EqValorTaxaServico': 0,
                                    'FaixaEtaria': 'ADT',
                                    'Quantidade': 1,
                                    'ValorFee': 1.0,
                                    'ValorRav': 0,
                                    'ValorTarifa': 347.9,
                                    'ValorTarifaNet': 347.9,
                                    'ValorTaxaAssento': 0,
                                    'ValorTaxaBagagem': 0,
                                    'ValorTaxaCombustivel': 0,
                                    'ValorTaxaEmbarque': 42.29,
                                    'ValorTaxaMenorDesacompanhado': 0,
                                    'ValorTaxaServico': 40
                                },
                                'PrecoBebe': None,
                                'PrecoCrianca': None,
                                'Tarifa': 0,
                                'TarifaOperadora': False,
                                'TarifaPrivada': False,
                                'Taxa': 82.29,
                                'Total': 431.19,
                                'TotalGeral': 431.19,
                                'TotalTarifa': 347.9,
                                'TotalTarifaNet': 347.9,
                                'TotalTaxaAssento': 0,
                                'TotalTaxaBagagem': 0,
                                'TotalTaxaDeCombustivel': 0,
                                'TotalTaxaEmbarque': 42.29,
                                'TotalTaxaMenorDesacompanhado': 0,
                                'TotalTaxaServico': 40,
                                'ValorEMD': 0,
                                'ValorFEE': 1.0,
                                'ValorRAV': 0
                            },
                            'TarifaAdulto': 347.9,
                            'TarifaBeba': 0,
                            'TarifaCrianca': 0,
                            'Tipo': 'OW'
                        },
                        {
                            'BagagemInclusa': True,
                            'BagagemIndicador': 3,
                            'BagagemPeso': 23,
                            'BagagemQuantidade': 2,
                            'BagagemUnidadeDeMedida': 'KG PER BAG',
                            'BaseTarifaria': 'ONJAAG4G',
                            'Cabine': 'Econômica',
                            'Classe': 'O',
                            'Familia': 'Max',
                            'FamiliaCodigo': 'MAX',
                            'Moeda': 'BRL',
                            'Perfil': None,
                            'Preco': {
                                'Id': 0,
                                'EqCambio': 0,
                                'EqMoeda': None,
                                'Moeda': 'BRL',
                                'PrecoAdulto': {
                                    'Id': 0,
                                    'EqValorTarifa': 0,
                                    'EqValorTaxaServico': 0,
                                    'FaixaEtaria': 'ADT',
                                    'Quantidade': 1,
                                    'ValorFee': 1.0,
                                    'ValorRav': 0,
                                    'ValorTarifa': 444.9,
                                    'ValorTarifaNet': 444.9,
                                    'ValorTaxaAssento': 0,
                                    'ValorTaxaBagagem': 0,
                                    'ValorTaxaCombustivel': 0,
                                    'ValorTaxaEmbarque': 42.29,
                                    'ValorTaxaMenorDesacompanhado': 0,
                                    'ValorTaxaServico': 44.49
                                },
                                'PrecoBebe': None,
                                'PrecoCrianca': None,
                                'Tarifa': 0,
                                'TarifaOperadora': False,
                                'TarifaPrivada': False,
                                'Taxa': 86.78,
                                'Total': 532.68,
                                'TotalGeral': 532.68,
                                'TotalTarifa': 444.9,
                                'TotalTarifaNet': 444.9,
                                'TotalTaxaAssento': 0,
                                'TotalTaxaBagagem': 0,
                                'TotalTaxaDeCombustivel': 0,
                                'TotalTaxaEmbarque': 42.29,
                                'TotalTaxaMenorDesacompanhado': 0,
                                'TotalTaxaServico': 44.49,
                                'ValorEMD': 0,
                                'ValorFEE': 1.0,
                                'ValorRAV': 0
                            },
                            'TarifaAdulto': 444.9,
                            'TarifaBeba': 0,
                            'TarifaCrianca': 0,
                            'Tipo': 'OW'
                        }
                    ],
                    'LocalizadorCompanhia': None,
                    'Numero': '1015',
                    'Origem': {
                        'Id': 0,
                        'CodigoIata': 'SDU',
                        'Descricao': 'SDU - RIO DE JANEIRO'
                    },
                    'QuantidadeParadas': 0,
                    'Referencia': None,
                    'ReferenciaDoSegmento': None,
                    'Segmento': 'I',
                    'Status': None
                }
            ]
        }
    ],
    'ViagensTrecho2': []
}
