trechos = {
    "ViagensTrecho1": [
        {
            "CiaMandatoria": {
                "Id": 0,
                "CodigoIata": "G3",
                "Descricao": "Gol Linhas Aéreas"
            },
            "Destino": {
                "Id": 0,
                "CodigoIata": "CGH",
                "Descricao": "CGH - SAO PAULO"
            },
            "Duracao": 65,
            "Fornecedor": {
                "Id": 0,
                "Codigo": 70,
                "Nome": "Gol_GWS"
            },
            "Id": 65585,
            "IdentificacaoDaViagem": "tQkAAB+LCAAAAAAABAC9ltuO2jAQhl9l5d5ySDgUNnchKCFVIBELq5VWq8okDlgb7MgOLRXigfocfbHaTkgWmlUXKhVxGHtmfuabsZIcgAkMvQEsYGgNMFLf9h4YMUw4aoAHzIEx0JThRsDo3YtQDIEBnC5ogOlrWoYGaqG1RPACp1SpjhHPMKFC4/kAfJH1MF6KtLGwLGcirEBYHa3TbWrDpj5YaJqh3sIzFx5N0/Smelee44soE3JkJZBzJIJ8kG8sIMOx+Mji/NkX03R6jnDl2wuawQQYnV6/da+dNv0UMRhRBkuGR1rUOnVYWmh7shBwhh3xYkGTOw+TDeR35q+fDEEunGbFaVag44dzUl0zuv2cdCJdutbtyzDrIkw3ekVDJtKl6z1pz3ZblaPLHIuSagjnC9GjgiIQLRLUZW902Zs3Ixv94RwV2dK0xW+gGh2cLDekRLZ/k2UpN9rt75SuYJNDEq3ovpUx+A0lCSavrZBuWyvWXqYJhVE7oWu6hSyEvC0cKSQbDHFI+601joWqDbc4kb09gBndSv2A0S1VlBFe09O/5yuXZIiRcjNgKMZ7tZznQRLp02DYQcNuvrapSJGbsXqBo9hVBykfuzUv2mVb582wIUOLH6lIfRbnr2xHMIXsdXfqYWCZhT+nGBdn8n/SJJhnsohjo5bG7dTTeItbaDy83mRvaZTMJU2uXdJ4rlPR6PdwMIxupXG678zGu2k2yY6fjcarG413PhpvWcEM4aoXoZthevUw06dbYKZw/5ZFiVyy5Moly9R8qljiVX+lx39neSntA3iEiUrW1WV3LSw7kSfEJRGS1cxRjBgiIYaBqE5dWVwSQ5LhpLhmHesFS70F3TFBgT4m1qgUPvdLjWzHzBBxTr+60dU6ju/dTfyp7/lOjaDq/dWS8+VoXCO25DsxVHq9nripJTV6cxTuGP+43mW+xVCkkpIb+mbLjZqi8mNtZvjb9aAzRDbiPvieqHoIuVZTa6h7bb1iHvRvR29JcAQjxNWzR4gpgZjnf8I/2taX4291wQnXtQkAAA==",
            "NumeroParadas": 0,
            "Origem": {
                "Id": 0,
                "CodigoIata": "SDU",
                "Descricao": "SDU - RIO DE JANEIRO"
            },
            "Preco": {
                "Id": 0,
                "EqCambio": 0,
                "EqMoeda": None,
                "Moeda": "BRL",
                "PrecoAdulto": {
                    "Id": 0,
                    "EqValorTarifa": 0,
                    "EqValorTaxaServico": 0,
                    "FaixaEtaria": "ADT",
                    "Quantidade": 1,
                    "ValorFee": 10.0,
                    "ValorRav": 0,
                    "ValorTarifa": 245.9,
                    "ValorTarifaNet": 245.9,
                    "ValorTaxaAssento": 0,
                    "ValorTaxaBagagem": 0,
                    "ValorTaxaCombustivel": 0,
                    "ValorTaxaEmbarque": 42.29,
                    "ValorTaxaMenorDesacompanhado": 0,
                    "ValorTaxaServico": 40
                },
                "PrecoBebe": None,
                "PrecoCrianca": None,
                "Tarifa": 0,
                "TarifaOperadora": False,
                "TarifaPrivada": False,
                "Taxa": 82.29,
                "Total": 338.19,
                "TotalGeral": 338.19,
                "TotalTarifa": 245.9,
                "TotalTarifaNet": 245.9,
                "TotalTaxaAssento": 0,
                "TotalTaxaBagagem": 0,
                "TotalTaxaDeCombustivel": 0,
                "TotalTaxaEmbarque": 42.29,
                "TotalTaxaMenorDesacompanhado": 0,
                "TotalTaxaServico": 40,
                "ValorEMD": 0,
                "ValorFEE": 10.0,
                "ValorRAV": 0
            },
            "Rota": None,
            "Segmento": "I",
            "SubFornecedor": None,
            "TempoDeDuracao": "01:05",
            "Voos": [
                {
                    "Id": 0,
                    "BagagemInclusa": False,
                    "BagagemIndicador": 2,
                    "BagagemPeso": 0,
                    "BagagemQuantidade": 0,
                    "BagagemUnidadeDeMedida": "KG Total",
                    "BaseTarifaria": [
                        {
                            "Id": 0,
                            "Classe": "",
                            "Codigo": "ONJAAG1G",
                            "Familia": "PO"
                        }
                    ],
                    "Cabine": "",
                    "Campo1": None,
                    "CiaMandatoria": {
                        "Id": 0,
                        "CodigoIata": "G3",
                        "Descricao": "Gol Linhas Aéreas"
                    },
                    "CiaOperacional": {
                        "Id": 0,
                        "CodigoIata": "G3",
                        "Descricao": "Gol Linhas Aéreas"
                    },
                    "Classe": "O",
                    "Companhia": None,
                    "Conexao": False,
                    "DataChegada": "/Date(1692283200000-0300)/",
                    "DataSaida": "/Date(1692279300000-0300)/",
                    "Destino": {
                        "Id": 0,
                        "CodigoIata": "CGH",
                        "Descricao": "CGH - SAO PAULO"
                    },
                    "Duracao": "01:05",
                    "Equipamento": "738",
                    "Escalas": None,
                    "Familia": "Promo",
                    "FamiliaCodigo": "PRO",
                    "GrupoDeSegmento": 0,
                    "HoraChegada": "1140",
                    "HoraSaida": "1035",
                    "Icone": "https://wooba-sandbox.travellink.com.br/Upload/logomarcas/companhiaico5.gif",
                    "Linha": None,
                    "ListaDeClasses": [
                        {
                            "BagagemInclusa": False,
                            "BagagemIndicador": 2,
                            "BagagemPeso": 0,
                            "BagagemQuantidade": 0,
                            "BagagemUnidadeDeMedida": "KG Total",
                            "BaseTarifaria": "ONJAAG1G",
                            "Cabine": "Econômica",
                            "Classe": "O",
                            "Familia": "Promo",
                            "FamiliaCodigo": "PRO",
                            "Moeda": "BRL",
                            "Perfil": None,
                            "Preco": {
                                "Id": 0,
                                "EqCambio": 0,
                                "EqMoeda": None,
                                "Moeda": "BRL",
                                "PrecoAdulto": {
                                    "Id": 0,
                                    "EqValorTarifa": 0,
                                    "EqValorTaxaServico": 0,
                                    "FaixaEtaria": "ADT",
                                    "Quantidade": 1,
                                    "ValorFee": 10.0,
                                    "ValorRav": 0,
                                    "ValorTarifa": 245.9,
                                    "ValorTarifaNet": 245.9,
                                    "ValorTaxaAssento": 0,
                                    "ValorTaxaBagagem": 0,
                                    "ValorTaxaCombustivel": 0,
                                    "ValorTaxaEmbarque": 42.29,
                                    "ValorTaxaMenorDesacompanhado": 0,
                                    "ValorTaxaServico": 40
                                },
                                "PrecoBebe": None,
                                "PrecoCrianca": None,
                                "Tarifa": 0,
                                "TarifaOperadora": False,
                                "TarifaPrivada": False,
                                "Taxa": 82.29,
                                "Total": 338.19,
                                "TotalGeral": 338.19,
                                "TotalTarifa": 245.9,
                                "TotalTarifaNet": 245.9,
                                "TotalTaxaAssento": 0,
                                "TotalTaxaBagagem": 0,
                                "TotalTaxaDeCombustivel": 0,
                                "TotalTaxaEmbarque": 42.29,
                                "TotalTaxaMenorDesacompanhado": 0,
                                "TotalTaxaServico": 40,
                                "ValorEMD": 0,
                                "ValorFEE": 10.0,
                                "ValorRAV": 0
                            },
                            "TarifaAdulto": 245.9,
                            "TarifaBeba": 0,
                            "TarifaCrianca": 0,
                            "Tipo": "OW"
                        },
                        {
                            "BagagemInclusa": False,
                            "BagagemIndicador": 2,
                            "BagagemPeso": 0,
                            "BagagemQuantidade": 0,
                            "BagagemUnidadeDeMedida": "KG Total",
                            "BaseTarifaria": "ONJAAI2G",
                            "Cabine": "Econômica",
                            "Classe": "O",
                            "Familia": "Light",
                            "FamiliaCodigo": "LIG",
                            "Moeda": "BRL",
                            "Perfil": None,
                            "Preco": {
                                "Id": 0,
                                "EqCambio": 0,
                                "EqMoeda": None,
                                "Moeda": "BRL",
                                "PrecoAdulto": {
                                    "Id": 0,
                                    "EqValorTarifa": 0,
                                    "EqValorTaxaServico": 0,
                                    "FaixaEtaria": "ADT",
                                    "Quantidade": 1,
                                    "ValorFee": 10.0,
                                    "ValorRav": 0,
                                    "ValorTarifa": 260.9,
                                    "ValorTarifaNet": 260.9,
                                    "ValorTaxaAssento": 0,
                                    "ValorTaxaBagagem": 0,
                                    "ValorTaxaCombustivel": 0,
                                    "ValorTaxaEmbarque": 42.29,
                                    "ValorTaxaMenorDesacompanhado": 0,
                                    "ValorTaxaServico": 40
                                },
                                "PrecoBebe": None,
                                "PrecoCrianca": None,
                                "Tarifa": 0,
                                "TarifaOperadora": False,
                                "TarifaPrivada": False,
                                "Taxa": 82.29,
                                "Total": 353.19,
                                "TotalGeral": 353.19,
                                "TotalTarifa": 260.9,
                                "TotalTarifaNet": 260.9,
                                "TotalTaxaAssento": 0,
                                "TotalTaxaBagagem": 0,
                                "TotalTaxaDeCombustivel": 0,
                                "TotalTaxaEmbarque": 42.29,
                                "TotalTaxaMenorDesacompanhado": 0,
                                "TotalTaxaServico": 40,
                                "ValorEMD": 0,
                                "ValorFEE": 10.0,
                                "ValorRAV": 0
                            },
                            "TarifaAdulto": 260.9,
                            "TarifaBeba": 0,
                            "TarifaCrianca": 0,
                            "Tipo": "OW"
                        },
                        {
                            "BagagemInclusa": True,
                            "BagagemIndicador": 3,
                            "BagagemPeso": 23,
                            "BagagemQuantidade": 1,
                            "BagagemUnidadeDeMedida": "KG PER BAG",
                            "BaseTarifaria": "ONJAAG3G",
                            "Cabine": "Econômica",
                            "Classe": "O",
                            "Familia": "Plus",
                            "FamiliaCodigo": "PLU",
                            "Moeda": "BRL",
                            "Perfil": None,
                            "Preco": {
                                "Id": 0,
                                "EqCambio": 0,
                                "EqMoeda": None,
                                "Moeda": "BRL",
                                "PrecoAdulto": {
                                    "Id": 0,
                                    "EqValorTarifa": 0,
                                    "EqValorTaxaServico": 0,
                                    "FaixaEtaria": "ADT",
                                    "Quantidade": 1,
                                    "ValorFee": 10.0,
                                    "ValorRav": 0,
                                    "ValorTarifa": 355.9,
                                    "ValorTarifaNet": 355.9,
                                    "ValorTaxaAssento": 0,
                                    "ValorTaxaBagagem": 0,
                                    "ValorTaxaCombustivel": 0,
                                    "ValorTaxaEmbarque": 42.29,
                                    "ValorTaxaMenorDesacompanhado": 0,
                                    "ValorTaxaServico": 40
                                },
                                "PrecoBebe": None,
                                "PrecoCrianca": None,
                                "Tarifa": 0,
                                "TarifaOperadora": False,
                                "TarifaPrivada": False,
                                "Taxa": 82.29,
                                "Total": 448.19,
                                "TotalGeral": 448.19,
                                "TotalTarifa": 355.9,
                                "TotalTarifaNet": 355.9,
                                "TotalTaxaAssento": 0,
                                "TotalTaxaBagagem": 0,
                                "TotalTaxaDeCombustivel": 0,
                                "TotalTaxaEmbarque": 42.29,
                                "TotalTaxaMenorDesacompanhado": 0,
                                "TotalTaxaServico": 40,
                                "ValorEMD": 0,
                                "ValorFEE": 10.0,
                                "ValorRAV": 0
                            },
                            "TarifaAdulto": 355.9,
                            "TarifaBeba": 0,
                            "TarifaCrianca": 0,
                            "Tipo": "OW"
                        },
                        {
                            "BagagemInclusa": True,
                            "BagagemIndicador": 3,
                            "BagagemPeso": 23,
                            "BagagemQuantidade": 2,
                            "BagagemUnidadeDeMedida": "KG PER BAG",
                            "BaseTarifaria": "ONJAAG4G",
                            "Cabine": "Econômica",
                            "Classe": "O",
                            "Familia": "Max",
                            "FamiliaCodigo": "MAX",
                            "Moeda": "BRL",
                            "Perfil": None,
                            "Preco": {
                                "Id": 0,
                                "EqCambio": 0,
                                "EqMoeda": None,
                                "Moeda": "BRL",
                                "PrecoAdulto": {
                                    "Id": 0,
                                    "EqValorTarifa": 0,
                                    "EqValorTaxaServico": 0,
                                    "FaixaEtaria": "ADT",
                                    "Quantidade": 1,
                                    "ValorFee": 10.0,
                                    "ValorRav": 0,
                                    "ValorTarifa": 452.9,
                                    "ValorTarifaNet": 452.9,
                                    "ValorTaxaAssento": 0,
                                    "ValorTaxaBagagem": 0,
                                    "ValorTaxaCombustivel": 0,
                                    "ValorTaxaEmbarque": 42.29,
                                    "ValorTaxaMenorDesacompanhado": 0,
                                    "ValorTaxaServico": 45.29
                                },
                                "PrecoBebe": None,
                                "PrecoCrianca": None,
                                "Tarifa": 0,
                                "TarifaOperadora": False,
                                "TarifaPrivada": False,
                                "Taxa": 87.58,
                                "Total": 550.48,
                                "TotalGeral": 550.48,
                                "TotalTarifa": 452.9,
                                "TotalTarifaNet": 452.9,
                                "TotalTaxaAssento": 0,
                                "TotalTaxaBagagem": 0,
                                "TotalTaxaDeCombustivel": 0,
                                "TotalTaxaEmbarque": 42.29,
                                "TotalTaxaMenorDesacompanhado": 0,
                                "TotalTaxaServico": 45.29,
                                "ValorEMD": 0,
                                "ValorFEE": 10.0,
                                "ValorRAV": 0
                            },
                            "TarifaAdulto": 452.9,
                            "TarifaBeba": 0,
                            "TarifaCrianca": 0,
                            "Tipo": "OW"
                        }
                    ],
                    "LocalizadorCompanhia": None,
                    "Numero": "1015",
                    "Origem": {
                        "Id": 0,
                        "CodigoIata": "SDU",
                        "Descricao": "SDU - RIO DE JANEIRO"
                    },
                    "QuantidadeParadas": 0,
                    "Referencia": None,
                    "ReferenciaDoSegmento": None,
                    "Segmento": "I",
                    "Status": None
                }
            ]
        },
    ]
}
